# Generated by Django 4.2.10 on 2024-02-21 14:53

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text="\n        Ensure the name of the file you upload is unique and descriptive. Look at existing uploaded files to see the recommended naming convention.\n        <br>\n        E.g. instead of calling a file 'lesson1.wav' you should call it 'pcr__y1__michaelmasterm__lesson1.wav' to make sure it's unique and easier to find the file when browsing a list of all files.\n        ", upload_to=pages.models.FileUpload.get_upload_to)),
                ('meta_created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
            options={
                'ordering': ['file', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('content_es', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content (Spanish)')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content (English)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('meta_slug', models.SlugField(max_length=500, unique=True, verbose_name='slug')),
                ('meta_created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('meta_lastupdated_datetime', models.DateTimeField(blank=True, null=True, verbose_name='last updated')),
                ('meta_firstpublished_datetime', models.DateTimeField(blank=True, null=True, verbose_name='first published')),
                ('meta_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('meta_lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_lastupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
