# Generated by Django 4.2.11 on 2024-03-26 13:41

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photographs')),
                ('description_es', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description (Spanish)')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description (English)')),
                ('acknowledgements', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, help_text='Check this box to include this photograph on the public website')),
                ('notes', models.TextField(blank=True, help_text='Notes are for admins only and will not be visible on the public website', null=True)),
                ('meta_created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('meta_lastupdated_datetime', models.DateTimeField(blank=True, null=True, verbose_name='last updated')),
                ('meta_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photographs_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('meta_lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photographs_lastupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographUserContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.TextField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('agree_to_ethics', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Notes are for admins only and will not be visible on the public website', null=True)),
                ('meta_created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('meta_lastupdated_datetime', models.DateTimeField(blank=True, null=True, verbose_name='last updated')),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photographusercontributions', to='photographs.photograph')),
            ],
        ),
    ]
