# Generated by Django 4.2.14 on 2024-07-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='image_name',
            field=models.CharField(blank=True, help_text='A brief name/title for the image', max_length=255, null=True),
        ),
    ]
