# Generated by Django 4.2.14 on 2024-07-31 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographs', '0002_photograph_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Notes are for admins only and will not be visible on the public website', null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='photograph',
            options={'ordering': ('group', 'order', 'meta_created_datetime')},
        ),
        migrations.AddField(
            model_name='photograph',
            name='order',
            field=models.IntegerField(blank=True, help_text='Photographs are ordered by their group, then by this order field (in ascending order), and then by date created.', null=True),
        ),
        migrations.AddField(
            model_name='photograph',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photographs', to='photographs.photographgroup'),
        ),
    ]
