# Generated by Django 4.2.16 on 2024-09-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographs', '0003_photographgroup_alter_photograph_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photograph',
            old_name='image_name',
            new_name='image_name_es',
        ),
        migrations.AddField(
            model_name='photograph',
            name='image_name_en',
            field=models.CharField(blank=True, help_text='A brief name/title for the image in English', max_length=255, null=True, verbose_name='Name (English)'),
        ),
    ]
