# Generated by Django 4.2.16 on 2024-09-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographs', '0004_rename_image_name_photograph_image_name_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='image_name_es',
            field=models.CharField(blank=True, help_text='A brief name/title for the image in Spanish', max_length=255, null=True, verbose_name='Name (Spanish)'),
        ),
    ]
